# Generated by Django 3.0.8 on 2020-07-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anime', '0003_auto_20200707_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Op_Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True)),
                ('opening', models.FileField(upload_to='Opening')),
            ],
        ),
        migrations.CreateModel(
            name='Personagem_Risada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=15, null=True)),
                ('imagem', models.ImageField(upload_to='Imagem')),
                ('onomatopeia', models.CharField(blank=True, max_length=15, null=True)),
                ('risada', models.FileField(upload_to='Risada')),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
        migrations.DeleteModel(
            name='Personagem',
        ),
    ]
