# Generated by Django 3.0.8 on 2020-07-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anime', '0004_auto_20200709_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='op_anime',
            name='nome',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
