# Generated by Django 3.0.7 on 2020-07-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anime', '0004_auto_20200709_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default=-1.0, upload_to='fotosPerfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personagem_risada',
            name='imagem',
            field=models.ImageField(upload_to='Pimagem'),
        ),
    ]
