# Generated by Django 3.0.7 on 2020-07-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_anime', '0005_auto_20200710_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default=-1.0, upload_to='fotPerfil'),
            preserve_default=False,
        ),
    ]
